{
  "os": "linux",
  "jdk": [
    "oraclejdk8"
  ],
  "dist": "trusty",
  "group": "stable",
  "addons": {
    "sonarcloud": {
      "token": {
        "secure": "A+ol9ujI8lK1TIlFBduPZtfOpj4emWMheQPeLDQkhDNqKspAiUvwFXNyoBo2AngpYcQX/mlYfQaRKjEluVR88LUhJYR84FM++V/NutmA5U10J9bEhxzcBdbWzzVr2yAVDeM8m9XjawJPh9Sy3SE4/C8aE5XoKD1p/jSlSGSE8J2IoBeA62WSnM0axM5lkpkxG+0ABZuJIQqy1o1G2mnpJuxjPu/RoS5cIxMSX1gYxAlHYNjGp5kd4MYEWu91K+lqjgIvft++Chi8qqu4DNjfS3l235kBVL+lYpRqW2uAvAmjzsCNUEMWTCm/xQB9IQVn2Lm5IbUA8m5HOtXvI95qAHthwVMZ9IzXuVlvzRW4/82TxQvFW35zEL00G/EE4mawwSfooM5In3iWzydcKwFc/p+KO+FAhBedUuW5dYb+X6fjuQ7sRReVCADskGXvwClqVVYKEN/+u6WUTJenoajIKeI6Ngyi6tP+y9eyr3Uq2XqP8IIUdOeEVPkYz5TlIRr26hy7x0zwaZNAgeDVUfoEvLh25hJZ3xRLq+efvktrgX8yRuq+koTcmVvyi8aQ/o46ETI5aCwkkFv3vlPwI65yDDO8FN+Tvy/vfzth4k1W/qvOwURjODlbwxc1LMfVmxSopM8IFy4rwd12p3/yxwu9J2RdggJEgI9GHMcIg5WiJ14="
      },
      "organization": "softserve-social-projects"
    }
  },
  "script": [
    "git fetch --unshallow",
    "mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dtest='greencity.service.impl.*Test' -Dsonar.projectKey=GreenCity -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=softserve-social-projects -Dsonar.sources='src/main/java/greencity/service' -Dsonar.tests='src/test/java/greencity/service/impl' -Dsonar.binaries=target/classes -Dsonar.dynamicAnalysis=reuseReports"
  ],
  ".result": "configured",
  "language": "java"
}
