{
  "os": "linux",
  "jdk": [
    "oraclejdk8"
  ],
  "dist": "trusty",
  "group": "stable",
  "addons": {
    "sonarcloud": {
      "token": {
        "secure": "$SONAR_TOKEN"
      },
      "organization": "softserve-social-projects"
    }
  },
  "script": [
    "git fetch --unshallow",
    "cat /home/travis/.sonarscanner/sonar-scanner/conf/sonar-scanner.properties"
  ],
  ".result": "configured",
  "language": "java"
}
